version: '3'

services:

#  BLUE PART
  blue_php:
    container_name: "blue_php-fpm"
    build:
      context: ../
      dockerfile: ./infra/php/Dockerfile
    environment:
      - APP_FOLDER=${APP_FOLDER}

  blue_app:
    container_name: "blue_nginx"
    build:
      context: ../
      dockerfile: ./infra/nginx/Dockerfile
    volumes:
      - ./logs/blue:/var/log
    environment:
      - ENV_NAME=blue
    depends_on:
      - blue_php

# GREEN PART
  green_php:
    container_name: "green_php-fpm"
    build:
      context: ../
      dockerfile: ./infra/php/Dockerfile
    environment:
      - APP_FOLDER=${APP_FOLDER}

  green_app:
    container_name: "green_nginx"
    build:
      context: ../
      dockerfile: ./infra/nginx/Dockerfile
    volumes:
      - ./logs/green:/var/log
    environment:
      - ENV_NAME=green
    depends_on:
      - green_php

# LOAD BALANCER
  bg:
    container_name: bg
    build:
      context: ./bluegreen_proxy
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - "${NGINX_PROD_PORT}:80"
      - "${NGINX_BETA_PORT}:8080"
    environment:
      - BLUE_NAME=blue
      - GREEN_NAME=green
      - LIVE=blue
    depends_on:
      - blue_app
      - green_app